### ISSUE TITLE
The blog site does not work

### ISSUE THREAD

**Issue by HasanAbdullah31** [hunter-college-ossd-spr19/gsvetleen-weekly#1]
When I navigate to https://hunter-college-ossd-spr19.github.io/gsvetleen-weekly/ I get a 404 error.

**Comment by stewartweiss** [comment]
This repository was supposed to be in a branch named gh-pages, but it was not. Perhaps because I did not create it as part of my batch script. Anyway, the gh-pages branch is now created and the pages are displayed now, so I am closing it.
